-- Bootstrap claroEmpresarial (SIR RAL/REC).
--
-- Prefer the Node generator (reads .env.local):
--   npm run db:bootstrap          # WSL local (sudo mariadb)
--   npm run db:bootstrap:sql        # stdout — prod: pipe to mariadb -u root -p
--
-- Produção: ajuste SIR_DB_GRANT_HOSTS no .env.local antes de gerar o SQL.
