import path from "path";
import { fileURLToPath } from "url";
import dotenv from "dotenv";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");

dotenv.config({ path: path.join(repoRoot, ".env.local") });
dotenv.config({ path: path.join(repoRoot, ".env") });

/** Lê variável de ambiente ou fallback; lança se ausente. */
function required(name, fallback) {
  const value = process.env[name] ?? fallback;
  if (!value) {
    throw new Error(`Missing ${name} in .env.local`);
  }
  return value;
}

/** Escapa valor para literal SQL entre aspas simples. */
function sqlLiteral(value) {
  return `'${String(value).replace(/\\/g, "\\\\").replace(/'/g, "''")}'`;
}

/** Escapa identificador MySQL com backticks. */
function quoteId(name) {
  return `\`${String(name).replace(/`/g, "``")}\``;
}

/** Hosts MySQL que recebem GRANT (SIR_DB_GRANT_HOSTS, separados por vírgula). */
function grantHosts() {
  const raw = process.env.SIR_DB_GRANT_HOSTS ?? "localhost,127.0.0.1";
  const hosts = raw
    .split(",")
    .map((host) => host.trim())
    .filter(Boolean);
  if (!hosts.length) {
    throw new Error("SIR_DB_GRANT_HOSTS must list at least one host");
  }
  return hosts;
}

/** Gera SQL de bootstrap do banco SIR (stdout) para execução como admin MySQL. */
function main() {
  const user = required("SIR_DB_USER", process.env.HFC_DB_USER);
  const password = required("SIR_DB_PASSWORD", process.env.HFC_DB_PASSWORD);
  const database = required("SIR_DB_NAME", "claroEmpresarial");
  const hosts = grantHosts();

  const lines = [
    `-- Generated by scripts/db/bootstrap-sir.mjs`,
    `-- Run as MySQL admin (prod or local), e.g.:`,
    `--   node scripts/db/bootstrap-sir.mjs | mariadb -u root -p`,
    `--   npm run db:bootstrap   # WSL local (pipe + sudo mariadb)`,
    ``,
    `CREATE DATABASE IF NOT EXISTS ${quoteId(database)}`,
    `  CHARACTER SET utf8mb4`,
    `  COLLATE utf8mb4_general_ci;`,
    ``,
  ];

  for (const host of hosts) {
    lines.push(
      `CREATE USER IF NOT EXISTS ${sqlLiteral(user)}@${sqlLiteral(host)} IDENTIFIED BY ${sqlLiteral(password)};`,
      `GRANT ALL PRIVILEGES ON ${quoteId(database)}.* TO ${sqlLiteral(user)}@${sqlLiteral(host)};`,
      ``,
    );
  }

  lines.push("FLUSH PRIVILEGES;", "");

  process.stdout.write(`${lines.join("\n")}\n`);
}

main();
