/** Textos das telas de autenticação, conta e administração (canônico GRNO). */
export const AUTH_COPY = {
  loginTitle: "Entrar",
  loginLead: "Use seu login corporativo (ex.: F104262).",
  registerTitle: "Criar conta",
  registerLead: "Cadastro sujeito à aprovação do administrador.",
  forgotTitle: "Esqueci a senha",
  forgotLead: "Informe seu login corporativo e escolha uma nova senha.",
  forgotSuccess: "Senha redefinida com sucesso.",
  forgotVerifyError: "Não foi possível redefinir. Verifique o login e se a conta está ativa.",
  passwordSelfResetNotificationTitle: "Senha redefinida pelo usuário",
  accountTitle: "Minha conta",
  accountLead: "Atualize seus dados cadastrais e a senha.",
  profileUpdateSuccess: "Dados atualizados.",
  settingsTitle: "Configurações",
  settingsLead: "Preferências de exibição e parâmetros operacionais.",
  settingsPreferencesTitle: "Preferências",
  settingsThemeLabel: "Tema da interface",
  settingsThemeHint: "Claro / escuro (navbar)",
  settingsSidebarLabel: "Menu lateral",
  settingsSidebarHint: "Expandido / recolhido (navbar)",
  settingsAccountLabel: "Conta e senha",
  settingsAccountCta: "Minha conta",
  settingsTourLabel: "Tour da aplicação",
  accountDataTitle: "Dados da conta",
  accountPasswordTitle: "Alterar senha",
  accountTourTitle: "Tour da aplicação",
  accountTourLead: "Revise os principais recursos da aplicação.",
  notificationsBellLabel: "Notificações",
  notificationsDropdownTitle: "Notificações",
  notificationsEmpty: "Nenhuma notificação.",
  notificationsLoading: "Carregando…",
  adminUsersTitle: "Usuários",
  adminUsersLead: "Aprovar cadastros e gerenciar acessos.",
  adminPendingTitle: "Cadastros pendentes",
  adminAllUsersTitle: "Todos os usuários",
  adminNotificationsTitle: "Notificações",
  adminNotificationsLead: "Criar e disparar avisos para todos os usuários.",
  notificationComposerTitle: "Nova notificação",
  notificationComposerLead: "A mensagem será entregue no sino de todos os usuários ativos.",
  notificationHistoryTitle: "Histórico",
  pendingBadge: "Aguardando aprovação",
  staffBadge: "Administrador",
  promoteStaff: "Promover a administrador",
  demoteStaff: "Remover privilégios de administrador",
  promoteStaffSuccess: "Usuário promovido a administrador.",
  demoteStaffSuccess: "Privilégios de administrador removidos.",
  promoteStaffConfirm:
    "Promover {name} ({corporateId}) a administrador? Terá acesso a usuários e notificações.",
  demoteStaffConfirm:
    "Remover privilégios de administrador de {name} ({corporateId})? Continuará como usuário comum.",
  promoteStaffConfirmAction: "Promover",
  demoteStaffConfirmAction: "Remover privilégios",
  deleteUserTitle: "Excluir usuário",
  deleteUserConfirm:
    "Excluir permanentemente {name} ({corporateId})? Esta ação não pode ser desfeita.",
  deleteUserConfirmAction: "Excluir permanentemente",
  deleteUserCancel: "Cancelar",
} as const;
