import type { GrbCommandPreset } from "@/lib/config/grb-types";

/** Comandos espelhados do sel_cmds do executar_comandos_telnet.php (AGG01.SLS). */
export const GRB_COMMAND_PRESETS: GrbCommandPreset[] = [
  {
    id: "show-interface-interface",
    label: "show interface (INTERFACE)",
    templateValue: "ISynu}show interface (INTERFACE)",
    requiresIp: false,
    requiresInterface: true,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-interface-interface-description",
    label: "show interface (INTERFACE) description",
    templateValue: "ISynu}show interface (INTERFACE) description",
    requiresIp: false,
    requiresInterface: true,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-interface-description",
    label: "show interface description",
    templateValue: "ISynu}show interface description",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-running-interface-interface",
    label: "show running interface (INTERFACE)",
    templateValue: "ISynu}show running interface (INTERFACE)",
    requiresIp: false,
    requiresInterface: true,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-ip-interface-brief",
    label: "show ip interface brief",
    templateValue: "ISynu}show ip interface brief",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-router-interface-interface",
    label: "show router interface (INTERFACE)",
    templateValue: "ISynu}show router interface (INTERFACE)",
    requiresIp: false,
    requiresInterface: true,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-router-interface-interface-detail",
    label: "show router interface (INTERFACE) detail",
    templateValue: "ISynu}show router interface (INTERFACE) detail",
    requiresIp: false,
    requiresInterface: true,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-atm-pvc",
    label: "show atm pvc",
    templateValue: "ISynu}show atm pvc",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-configuration",
    label: "show configuration",
    templateValue: "ISynu}show configuration",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-configuration-running-config",
    label: "show configuration running-config",
    templateValue: "ISynu}show configuration running-config",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-ip-pim-interface-interface",
    label: "show ip pim interface (INTERFACE)",
    templateValue: "ISynu}show ip pim interface (INTERFACE)",
    requiresIp: false,
    requiresInterface: true,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-ip-pim-neighbor-interface",
    label: "show ip pim neighbor (INTERFACE)",
    templateValue: "ISynu}show ip pim neighbor (INTERFACE)",
    requiresIp: false,
    requiresInterface: true,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-ip-pim-vrf-vrf-interface-interface",
    label: "show ip pim vrf (VRF) interface (INTERFACE)",
    templateValue: "ISynu}show ip pim vrf (VRF) interface (INTERFACE)",
    requiresIp: false,
    requiresInterface: true,
    requiresVrf: true,
    requiresWord: false,
  },
  {
    id: "show-bgp-vrf-vrf-summary",
    label: "show bgp vrf (VRF) summary",
    templateValue: "ISynu}show bgp vrf (VRF) summary",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: true,
    requiresWord: false,
  },
  {
    id: "show-bgp-vrf-vrf-neighbors-ip-advertised-routes",
    label: "show bgp vrf (VRF) neighbors (IP) advertised-routes",
    templateValue: "ISynu}show bgp vrf (VRF) neighbors (IP) advertised-routes",
    requiresIp: true,
    requiresInterface: false,
    requiresVrf: true,
    requiresWord: false,
  },
  {
    id: "show-bgp-vrf-vrf-neighbors-ip-routes",
    label: "show bgp vrf (VRF) neighbors (IP) routes",
    templateValue: "ISynu}show bgp vrf (VRF) neighbors (IP) routes",
    requiresIp: true,
    requiresInterface: false,
    requiresVrf: true,
    requiresWord: false,
  },
  {
    id: "show-bgp-vrf-vrf-ip",
    label: "show bgp vrf (VRF) (IP)",
    templateValue: "ISynu}show bgp vrf (VRF) (IP)",
    requiresIp: true,
    requiresInterface: false,
    requiresVrf: true,
    requiresWord: false,
  },
  {
    id: "show-bgp-vrf-vrf",
    label: "show bgp vrf (VRF)",
    templateValue: "ISynu}show bgp vrf (VRF)",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: true,
    requiresWord: false,
  },
  {
    id: "show-ip-vrf-vrf",
    label: "show ip vrf (VRF)",
    templateValue: "ISynu}show ip vrf (VRF)",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: true,
    requiresWord: false,
  },
  {
    id: "show-ip-vrf-detail-vrf",
    label: "show ip vrf detail (VRF)",
    templateValue: "ISynu}show ip vrf detail (VRF)",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: true,
    requiresWord: false,
  },
  {
    id: "show-ip-vrf-interfaces",
    label: "show ip vrf interfaces",
    templateValue: "ISynu}show ip vrf interfaces",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-ip-vrf-interfaces-vrf",
    label: "show ip vrf interfaces (VRF)",
    templateValue: "ISynu}show ip vrf interfaces (VRF)",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: true,
    requiresWord: false,
  },
  {
    id: "show-running-config-vrf-vrf",
    label: "show running-config vrf (VRF)",
    templateValue: "ISynu}show running-config vrf (VRF)",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: true,
    requiresWord: false,
  },
  {
    id: "show-ip-arp",
    label: "show ip arp",
    templateValue: "ISynu}show ip arp",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-ip-arp-interface",
    label: "show ip arp (INTERFACE)",
    templateValue: "ISynu}show ip arp (INTERFACE)",
    requiresIp: false,
    requiresInterface: true,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-ip-arp-vrf-vrf",
    label: "show ip arp vrf (VRF)",
    templateValue: "ISynu}show ip arp vrf (VRF)",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: true,
    requiresWord: false,
  },
  {
    id: "show-ip-arp-vrf-vrf-interface",
    label: "show ip arp vrf (VRF) (INTERFACE)",
    templateValue: "ISynu}show ip arp vrf (VRF) (INTERFACE)",
    requiresIp: false,
    requiresInterface: true,
    requiresVrf: true,
    requiresWord: false,
  },
  {
    id: "show-ip-ospf-interface-brief",
    label: "show ip ospf interface brief",
    templateValue: "ISynu}show ip ospf interface brief",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-ip-ospf-interface-interface",
    label: "show ip ospf interface (INTERFACE)",
    templateValue: "ISynu}show ip ospf interface (INTERFACE)",
    requiresIp: false,
    requiresInterface: true,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-ip-ospf-neighbor",
    label: "show ip ospf neighbor",
    templateValue: "ISynu}show ip ospf neighbor",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-ip-ospf-neighbor-interface",
    label: "show ip ospf neighbor (INTERFACE)",
    templateValue: "ISynu}show ip ospf neighbor (INTERFACE)",
    requiresIp: false,
    requiresInterface: true,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-ip-bgp-summary",
    label: "show ip bgp summary",
    templateValue: "ISynu}show ip bgp summary",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-ip-bgp-ip",
    label: "show ip bgp (IP)",
    templateValue: "ISynu}show ip bgp (IP)",
    requiresIp: true,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-ip-bgp-neighbors-ip",
    label: "show ip bgp neighbors (IP)",
    templateValue: "ISynu}show ip bgp neighbors (IP)",
    requiresIp: true,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-ip-bgp-vpnv4-vrf-vrf",
    label: "show ip bgp vpnv4 vrf (VRF)",
    templateValue: "ISynu}show ip bgp vpnv4 vrf (VRF)",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: true,
    requiresWord: false,
  },
  {
    id: "show-ip-bgp-vpnv4-vrf-vrf-summary",
    label: "show ip bgp vpnv4 vrf (VRF) summary",
    templateValue: "ISynu}show ip bgp vpnv4 vrf (VRF) summary",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: true,
    requiresWord: false,
  },
  {
    id: "show-ip-bgp-vpnv4-vrf-vrf-neighbors-ip",
    label: "show ip bgp vpnv4 vrf (VRF) neighbors (IP)",
    templateValue: "ISynu}show ip bgp vpnv4 vrf (VRF) neighbors (IP)",
    requiresIp: true,
    requiresInterface: false,
    requiresVrf: true,
    requiresWord: false,
  },
  {
    id: "show-ip-bgp-vpnv4-vrf-vrf-neighbors-ip-advertised-routes",
    label: "show ip bgp vpnv4 vrf (VRF) neighbors (IP) advertised-routes",
    templateValue: "ISynu}show ip bgp vpnv4 vrf (VRF) neighbors (IP) advertised-routes",
    requiresIp: true,
    requiresInterface: false,
    requiresVrf: true,
    requiresWord: false,
  },
  {
    id: "show-ip-bgp-vpnv4-vrf-vrf-neighbors-ip-routes",
    label: "show ip bgp vpnv4 vrf (VRF) neighbors (IP) routes",
    templateValue: "ISynu}show ip bgp vpnv4 vrf (VRF) neighbors (IP) routes",
    requiresIp: true,
    requiresInterface: false,
    requiresVrf: true,
    requiresWord: false,
  },
  {
    id: "show-ip-bgp-vpnv4-vrf-vrf-ip",
    label: "show ip bgp vpnv4 vrf (VRF) (IP)",
    templateValue: "ISynu}show ip bgp vpnv4 vrf (VRF) (IP)",
    requiresIp: true,
    requiresInterface: false,
    requiresVrf: true,
    requiresWord: false,
  },
  {
    id: "show-ip-prefix-list",
    label: "show ip prefix-list",
    templateValue: "ISynu}show ip prefix-list",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-ip-route-ip",
    label: "show ip route (IP)",
    templateValue: "ISynu}show ip route (IP)",
    requiresIp: true,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-ip-route-vrf-vrf",
    label: "show ip route vrf (VRF)",
    templateValue: "ISynu}show ip route vrf (VRF)",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: true,
    requiresWord: false,
  },
  {
    id: "show-ip-route-vrf-vrf-ip",
    label: "show ip route vrf (VRF) (IP)",
    templateValue: "ISynu}show ip route vrf (VRF) (IP)",
    requiresIp: true,
    requiresInterface: false,
    requiresVrf: true,
    requiresWord: false,
  },
  {
    id: "show-route",
    label: "show route",
    templateValue: "ISynu}show route",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-route-ip",
    label: "show route (IP)",
    templateValue: "ISynu}show route (IP)",
    requiresIp: true,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-route-vrf-vrf",
    label: "show route vrf (VRF)",
    templateValue: "ISynu}show route vrf (VRF)",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: true,
    requiresWord: false,
  },
  {
    id: "show-route-vrf-vrf-ip",
    label: "show route vrf (VRF) (IP)",
    templateValue: "ISynu}show route vrf (VRF) (IP)",
    requiresIp: true,
    requiresInterface: false,
    requiresVrf: true,
    requiresWord: false,
  },
  {
    id: "show-pim-vrf-vrf-neighbor",
    label: "show pim vrf (VRF) neighbor",
    templateValue: "ISynu}show pim vrf (VRF) neighbor",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: true,
    requiresWord: false,
  },
  {
    id: "show-pim-vrf-vrf-group-map",
    label: "show pim vrf (VRF) group-map",
    templateValue: "ISynu}show pim vrf (VRF) group-map",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: true,
    requiresWord: false,
  },
  {
    id: "show-mfib-vrf-vrf-route",
    label: "show mfib vrf (VRF) route",
    templateValue: "ISynu}show mfib vrf (VRF) route",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: true,
    requiresWord: false,
  },
  {
    id: "show-ip-cef-ip",
    label: "show ip cef (IP)",
    templateValue: "ISynu}show ip cef (IP)",
    requiresIp: true,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-ip-cef-interface",
    label: "show ip cef (INTERFACE)",
    templateValue: "ISynu}show ip cef (INTERFACE)",
    requiresIp: false,
    requiresInterface: true,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-ip-cef-vrf-vrf-ip",
    label: "show ip cef vrf (VRF) (IP)",
    templateValue: "ISynu}show ip cef vrf (VRF) (IP)",
    requiresIp: true,
    requiresInterface: false,
    requiresVrf: true,
    requiresWord: false,
  },
  {
    id: "show-ip-cef-vrf-vrf-interface",
    label: "show ip cef vrf (VRF) (INTERFACE)",
    templateValue: "ISynu}show ip cef vrf (VRF) (INTERFACE)",
    requiresIp: false,
    requiresInterface: true,
    requiresVrf: true,
    requiresWord: false,
  },
  {
    id: "show-ip-prefix-list-word",
    label: "show ip prefix-list (WORD)",
    templateValue: "ISynu}show ip prefix-list (WORD)",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: true,
  },
  {
    id: "show-ip-extcommunity-list-word",
    label: "show ip extcommunity-list (WORD)",
    templateValue: "ISynu}show ip extcommunity-list (WORD)",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: true,
  },
  {
    id: "show-ip-community-list-word",
    label: "show ip community-list (WORD)",
    templateValue: "ISynu}show ip community-list (WORD)",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: true,
  },
  {
    id: "show-access-list-word",
    label: "show access-list (WORD)",
    templateValue: "ISynu}show access-list (WORD)",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: true,
  },
  {
    id: "show-class-map-word",
    label: "show class-map (WORD)",
    templateValue: "ISynu}show class-map (WORD)",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: true,
  },
  {
    id: "show-route-map-word",
    label: "show route-map (WORD)",
    templateValue: "ISynu}show route-map (WORD)",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: true,
  },
  {
    id: "show-policy-map-word",
    label: "show policy-map (WORD)",
    templateValue: "ISynu}show policy-map (WORD)",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: true,
  },
  {
    id: "show-policy-map-interface-interface",
    label: "show policy-map interface (INTERFACE)",
    templateValue: "ISynu}show policy-map interface (INTERFACE)",
    requiresIp: false,
    requiresInterface: true,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-running-config-map-class-frame-relay-word",
    label: "show running-config map-class frame-relay (WORD)",
    templateValue: "ISynu}show running-config map-class frame-relay (WORD)",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: true,
  },
  {
    id: "show-frame-relay-fragment-interface-interface",
    label: "show frame-relay fragment interface (INTERFACE)",
    templateValue: "ISynu}show frame-relay fragment interface (INTERFACE)",
    requiresIp: false,
    requiresInterface: true,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-frame-relay-pvc-interface-interface",
    label: "show frame-relay pvc interface (INTERFACE)",
    templateValue: "ISynu}show frame-relay pvc interface (INTERFACE)",
    requiresIp: false,
    requiresInterface: true,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-frame-relay-map",
    label: "show frame-relay map",
    templateValue: "ISynu}show frame-relay map",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-ppp-multilink-interface-interface",
    label: "show ppp multilink interface (INTERFACE)",
    templateValue: "ISynu}show ppp multilink interface (INTERFACE)",
    requiresIp: false,
    requiresInterface: true,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-controllers-e1",
    label: "show controllers E1",
    templateValue: "ISynu}show controllers E1",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-controllers-atm",
    label: "show controllers atm",
    templateValue: "ISynu}show controllers atm",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-controllers-pos",
    label: "show controllers pos",
    templateValue: "ISynu}show controllers pos",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-controllers-serial",
    label: "show controllers serial",
    templateValue: "ISynu}show controllers serial",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-controllers-sonet",
    label: "show controllers sonet",
    templateValue: "ISynu}show controllers sonet",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-controllers-gigabitethernet",
    label: "show controllers GigabitEthernet",
    templateValue: "ISynu}show controllers GigabitEthernet",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-controllers-fia",
    label: "show controllers fia",
    templateValue: "ISynu}show controllers fia",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-controllers-cbus",
    label: "show controllers cbus",
    templateValue: "ISynu}show controllers cbus",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-cef-linecard",
    label: "show cef linecard",
    templateValue: "ISynu}show cef linecard",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-diag",
    label: "show diag",
    templateValue: "ISynu}show diag",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-diag-word",
    label: "show diag (WORD)",
    templateValue: "ISynu}show diag (WORD)",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: true,
  },
  {
    id: "show-diag-summary",
    label: "show diag summary",
    templateValue: "ISynu}show diag summary",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-led",
    label: "show led",
    templateValue: "ISynu}show led",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-environment-all",
    label: "show environment all",
    templateValue: "ISynu}show environment all",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-environment-word",
    label: "show environment (WORD)",
    templateValue: "ISynu}show environment (WORD)",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: true,
  },
  {
    id: "show-context-summary",
    label: "show context summary",
    templateValue: "ISynu}show context summary",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-gsr",
    label: "show gsr",
    templateValue: "ISynu}show gsr",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-redundancy",
    label: "show redundancy",
    templateValue: "ISynu}show redundancy",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-logging",
    label: "show logging",
    templateValue: "ISynu}show logging",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "show-version",
    label: "show version",
    templateValue: "ISynu}show version",
    requiresIp: false,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "ping-ip",
    label: "ping (IP)",
    templateValue: "ISvotmping (IP)",
    requiresIp: true,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "ping-ip-source-interface",
    label: "ping (IP) source (INTERFACE)",
    templateValue: "ISvotmping (IP) source (INTERFACE)",
    requiresIp: true,
    requiresInterface: true,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "ping-vrf-vrf-ip",
    label: "ping vrf (VRF) (IP)",
    templateValue: "ISvotmping vrf (VRF) (IP)",
    requiresIp: true,
    requiresInterface: false,
    requiresVrf: true,
    requiresWord: false,
  },
  {
    id: "ping-vrf-vrf-ip-word",
    label: "ping vrf (VRF) (IP) (WORD)",
    templateValue: "ISvotmping vrf (VRF) (IP) (WORD)",
    requiresIp: true,
    requiresInterface: false,
    requiresVrf: true,
    requiresWord: true,
  },
  {
    id: "ping-vrf-vrf-ip-source-interface",
    label: "ping vrf (VRF) (IP) source (INTERFACE)",
    templateValue: "ISvotmping vrf (VRF) (IP) source (INTERFACE)",
    requiresIp: true,
    requiresInterface: true,
    requiresVrf: true,
    requiresWord: false,
  },
  {
    id: "traceroute-ip",
    label: "traceroute (IP)",
    templateValue: "ISzxgitraceroute (IP)",
    requiresIp: true,
    requiresInterface: false,
    requiresVrf: false,
    requiresWord: false,
  },
  {
    id: "traceroute-vrf-vrf-ip",
    label: "traceroute vrf (VRF) (IP)",
    templateValue: "ISzxgitraceroute vrf (VRF) (IP)",
    requiresIp: true,
    requiresInterface: false,
    requiresVrf: true,
    requiresWord: false,
  },
];
