import type { TelnetCommandPreset } from "@/lib/config/grb-telnet-types";

/** Comandos Nokia SR OS exclusivos para STAFF no fluxo TELNET. */
export const TELNET_STAFF_COMMANDS: readonly TelnetCommandPreset[] = [
  {
    id: "nokia-show-router-interface",
    label: "show router interface (INTERFACE)",
    category: "interfaces",
    templateValue: "ISynu}show router interface (INTERFACE)",
    requiresInterface: true,
    staffOnly: true,
    nokiaOnly: true,
  },
  {
    id: "nokia-show-router-interface-detail",
    label: "show router interface (INTERFACE) detail",
    category: "interfaces",
    templateValue: "ISynu}show router interface (INTERFACE) detail",
    requiresInterface: true,
    staffOnly: true,
    nokiaOnly: true,
  },
  {
    id: "nokia-bgp-neighbor-ipv4-received",
    label: "show router bgp neighbor (IP) received-routes",
    category: "bgp",
    templateValue: "ISynu}show router bgp neighbor (IP) received-routes",
    requiresIp: true,
    staffOnly: true,
    nokiaOnly: true,
  },
  {
    id: "nokia-bgp-neighbor-ipv6-received",
    label: "show router bgp neighbor (IPv6) received-routes ipv6",
    category: "bgp",
    templateValue: "ISynu}show router bgp neighbor (IPv6) received-routes ipv6",
    requiresIpv6: true,
    staffOnly: true,
    nokiaOnly: true,
  },
  {
    id: "nokia-bgp-neighbor-ipv4-advertised",
    label: "show router bgp neighbor (IP) advertised-routes",
    category: "bgp",
    templateValue: "ISynu}show router bgp neighbor (IP) advertised-routes",
    requiresIp: true,
    staffOnly: true,
    nokiaOnly: true,
  },
  {
    id: "nokia-bgp-neighbor-ipv6-advertised",
    label: "show router bgp neighbor (IPv6) advertised-routes ipv6",
    category: "bgp",
    templateValue: "ISynu}show router bgp neighbor (IPv6) advertised-routes ipv6",
    requiresIpv6: true,
    staffOnly: true,
    nokiaOnly: true,
  },
  {
    id: "nokia-bgp-vrf-neighbor-ipv4-received",
    label: "show router (VRF) bgp neighbor (IP) received-routes",
    category: "bgp",
    templateValue: "ISynu}show router (VRF) bgp neighbor (IP) received-routes",
    requiresIp: true,
    requiresVrf: true,
    staffOnly: true,
    nokiaOnly: true,
  },
  {
    id: "nokia-bgp-vrf-neighbor-ipv4-advertised",
    label: "show router (VRF) bgp neighbor (IP) advertised-routes",
    category: "bgp",
    templateValue: "ISynu}show router (VRF) bgp neighbor (IP) advertised-routes",
    requiresIp: true,
    requiresVrf: true,
    staffOnly: true,
    nokiaOnly: true,
  },
];
