import { METRIC_LABELS } from "@/lib/config/metric-labels";

/** Textos das páginas de relatórios operacionais. */
export const RELATORIOS_COPY = {
  hubTitle: "Relatórios",
  hubDescription:
    "Escolha o tipo de relatório. Novas análises serão adicionadas aqui conforme forem disponibilizadas.",
  hubOpenAction: "Abrir",
  hubComingSoon: "Em breve",
  exportHubLink: "Exportação CSV",
  exportSectionTitle: "Exportação CSV",
  exportHubSectionLead: "Planilhas de RAL, REC e inventário PME com filtros opcionais.",
  tratativasPageTitle: "BSOD",
  tratativasPageDescription:
    "Coorte de chamados iniciados no período: funil até conclusão e atividade diária.",
  exportPageTitle: "Exportação CSV",
  exportPageDescription: "Baixe planilhas filtradas de RAL, REC e inventário PME.",
  backToHub: "Voltar aos relatórios",
  tratativasSectionTitle: "Resumo da coorte",
  tratativasSectionLead:
    "KPIs e funil dos chamados iniciados no período. A série diária mostra atividade registrada no mesmo intervalo.",
  applyFilters: "Atualizar",
  presetDays: (days: number) => `Últimos ${days} dias`,
  dailyChartTitle: "Atividade por dia",
  dailyChartLead: "Eventos registrados em cada dia (não limitado à coorte).",
  eventMixTitle: "Distribuição por etapa",
  eventMixLead: "Quantidade de chamados da coorte que atingiram cada etapa.",
  funnelTitle: "Funil da coorte",
  funnelLead: "Conversão dos mesmos chamados: assumir → VT → validação → conclusão.",
  operatorsTitle: "Operadores",
  operatorsLead: "Quem mais registrou VT e concluiu chamados no período.",
  symptomsTitle: "Reclamações por sintoma",
  symptomsLead: "Sintoma informado nas VTs da coorte.",
  topClientsTitle: "Clientes com mais VTs",
  topClientsLead: "Contratos (ou MACs) com mais acionamentos na coorte.",
  emptyTratativas: "Nenhum chamado iniciado no período selecionado.",
  emptyDaily: "Sem atividade diária para exibir.",
  emptyOperators: "Nenhum acionamento ou conclusão atribuído a operadores.",
  emptySymptoms: "Nenhuma VT com sintoma registrado na coorte.",
  emptyTopClients: "Nenhum cliente com VT registrada na coorte.",
  sdhPageTitle: "SDH",
  sdhPageDescription:
    "Análise do backlog ativo de alarmes SDH (TMIP >6h), idade, DDD/gerência e atividade de tratativa no período.",
  sdhSectionTitle: "Backlog e tratativas",
  sdhSectionLead:
    "KPIs do backlog atual e atividade histórica (assunções, observações e encerramentos) no período.",
  sdhEmpty: "Nenhum alarme SDH ativo para os filtros selecionados.",
  sdhEmptyDaily: "Sem eventos de tratativa no período.",
  sdhEmptyOperators: "Nenhum login registrou eventos no período.",
  sdhEmptyRank: "Sem dados para este ranking.",
  sdhKpiTotal: "Ativos",
  sdhKpiPending: "Pendentes",
  sdhKpiInProgress: "Em tratativa",
  sdhKpiNeverTouched: "Nunca tratados",
  sdhKpiStarts: "Assumidos",
  sdhKpiObservations: "Observações",
  sdhKpiLegacyUpdates: "Atualizações (legado)",
  sdhKpiCloses: "Encerramentos",
  sdhStatusTitle: "Distribuição do backlog",
  sdhStatusLead: "Pendentes versus alarmes em tratativa no momento.",
  sdhAgeTitle: "Idade dos alarmes",
  sdhAgeLead: "Tempo desde data_alarme até agora.",
  sdhDailyTitle: "Eventos por dia",
  sdhDailyLead: "Assunções, observações e encerramentos registrados em cada dia.",
  sdhDddTitle: "Por DDD",
  sdhDddLead: "Concentração do backlog ativo por código de área.",
  sdhVendorTitle: "Por gerência",
  sdhVendorLead: "Datacom, Tellabs e Alcatel.",
  sdhMunicipioTitle: "Por município",
  sdhMunicipioLead: "Municípios com mais alarmes ativos.",
  sdhAlarmeTitle: "Por tipo de alarme",
  sdhAlarmeLead: "Textos de alarme mais frequentes no backlog.",
  sdhOperatorsTitle: "Logins no período",
  sdhOperatorsLead: "Quem mais assumiu, observou ou encerrou tratativas.",
  sdhOpenMonitor: "Abrir monitoramento SDH",
  sdhExportCsv: "Exportar CSV",
  sirPageTitle: "SIR",
  sirPageDescription:
    "Backlog ativo de RAL e REC, idade em aberto, aberturas no período e recortes por CF, tipo e localidade.",
  sirSectionTitle: "Backlog e aberturas",
  sirSectionLead:
    "Indicadores por domínio (RAL e REC separados). Sem tendência de encerramento — não há timestamp histórico confiável.",
  sirEmpty: "Nenhum registro ATIVO para os filtros selecionados.",
  sirEmptyDaily: "Sem aberturas no período.",
  sirEmptyRank: "Sem dados para este ranking.",
  sirKpiRalTotal: "RAL ativos",
  sirKpiRalPending: "RAL pendentes",
  sirKpiRalTreatment: "RAL em tratativa",
  sirKpiRalOpenings: "RAL abertos no período",
  sirKpiRecTotal: "REC ativos",
  sirKpiRecPending: "REC pendentes",
  sirKpiRecTreatment: "REC em tratativa",
  sirKpiRecOpenings: "REC abertos no período",
  sirAgeTitle: "Idade dos abertos",
  sirAgeLead: "Tempo desde a abertura até agora (somente status ATIVO).",
  sirDailyTitle: "Aberturas por dia",
  sirDailyLead: "Registros cuja data de abertura cai no período.",
  sirCfTitle: "Por CF executante",
  sirCfLead: "CFs com mais registros ativos.",
  sirTipoTitle: "Por classificação",
  sirTipoLead: "Tipos RAL e prefixos REC/DSR/TCQ no backlog.",
  sirDddTitle: "Por DDD",
  sirDddLead: "Concentração do backlog ativo por agrupamento operacional.",
  sirOpenMonitor: "Abrir monitoramento SIR",
  sirExportCsv: "Exportar CSV",
  sirDomainLabel: "Domínio",
  sirTreatmentLabel: "Tratativa",
  vendorLabel: "Gerência",
  dddLabel: "DDD",
  allVendors: "Todas as gerências",
  allDdds: "Todos os DDDs",
  chamadosTitle: "Chamados por status",
  chamadosLead:
    "Listagem da coorte (iniciados no período). O filtro de status afeta apenas esta tabela — KPIs e gráficos permanecem da coorte completa.",
  emptyChamados: "Nenhum chamado encontrado para o filtro selecionado.",
  chamadosColMac: "MAC",
  chamadosColStatus: "Status",
  chamadosColOperador: "Operador",
  chamadosColAssumido: "Assumido em",
  chamadosColRegistrado: "Registrado em",
  chamadosColValidado: "Validado em",
  chamadosColConcluido: "Concluído em",
  chamadosStatusAll: "Todos",
  chamadosShowFca: "Ver FCA",
  chamadosHideFca: "Ocultar FCA",
  chamadosFcaTitle: "FCA da validação",
  chamadosFato: "Fato",
  chamadosCausa: "Causa",
  chamadosAcao: "Ação",
  durationHint: (minutes: number) => `Tempo médio até conclusão (coorte): ${minutes} min`,
  durationUnavailable: "Tempo médio indisponível (sem conclusões na coorte).",
  kpiAssuncoes: "Chamados da coorte",
  kpiAssuncoesHint: "Iniciados no período (denominador do funil)",
  kpiAcionamentos: "Com VT",
  kpiAcionamentosHint: "Chamados da coorte que registraram visita técnica",
  kpiValidacoes: "Com validação",
  kpiValidacoesHint: "Chamados da coorte com parecer do técnico",
  kpiConcluidas: "Concluídos",
  kpiConcluidasHint: "Chamados da coorte encerrados até o fim do período",
  kpiAprovadas: "Aprovadas",
  kpiReprovadas: "Reprovadas",
  operatorAcionamentos: "Acionamentos",
  operatorConcluidas: "Conclusões",
  exportCsv: "Baixar CSV",
  exportAllHint: "Exporta todos os registros que correspondem aos filtros selecionados.",
  filtersLabel: "Filtros",
  statusLabel: "Status",
  tipoLabel: "Tipo",
  cfLabel: "CF executante",
  cfPlaceholder: "Opcional",
  cmtsLabel: "CMTS",
  cmtsPlaceholder: "Opcional",
  nodeLabel: "Node",
  nodePlaceholder: "Opcional",
  saudeLabel: "Saúde",
  vlanLabel: "VLAN BSOD",
  allTypes: "Todos",
  allHealth: "Todas",
  allVlan: "Todas",
} as const;

/** Metadados dos relatórios CSV disponíveis. */
export const RELATORIO_EXPORT_META = {
  ral: {
    title: METRIC_LABELS.sir.ral,
    description: "Listagem de RAL com status, tipo, CF, designação e datas.",
    exportPath: "/api/export/sir/rals",
    scope: "ral" as const,
  },
  rec: {
    title: METRIC_LABELS.sir.recScope,
    description: "Listagem REC/DSR/TCQ com cliente, designação, CF e datas.",
    exportPath: "/api/export/sir/recs",
    scope: "rec" as const,
  },
  bsod: {
    title: METRIC_LABELS.bsod.inventario,
    description: "Inventário PME com status, endereço, VLAN e métricas de sinal.",
    exportPath: "/api/export/bsod",
  },
} as const;
