import { METRIC_LABELS } from "@/lib/config/metric-labels";

/** Textos das páginas de relatórios operacionais. */
export const RELATORIOS_COPY = {
  hubTitle: "Relatórios",
  hubDescription:
    "Escolha o tipo de relatório. Novas análises serão adicionadas aqui conforme forem disponibilizadas.",
  hubOpenAction: "Abrir",
  hubComingSoon: "Em breve",
  exportHubLink: "Exportação CSV",
  exportSectionTitle: "Exportação CSV",
  exportHubSectionLead: "Planilhas de RAL, REC e inventário PME com filtros opcionais.",
  tratativasPageTitle: "BSOD",
  tratativasPageDescription:
    "Acompanhamento operacional: chamados assumidos, VTs registradas, validações e encerramentos.",
  exportPageTitle: "Exportação CSV",
  exportPageDescription: "Baixe planilhas filtradas de RAL, REC e inventário PME.",
  backToHub: "Voltar aos relatórios",
  tratativasSectionTitle: "Resumo operacional",
  tratativasSectionLead:
    "Indicadores do fluxo de tratativa no período — do chamado assumido até a conclusão.",
  periodLabel: "Período",
  recordKindLabel: "Tipo de registro",
  applyFilters: "Atualizar",
  presetDays: (days: number) => `Últimos ${days} dias`,
  periodSummary: (period: string, scope: string) => `${period} · ${scope}`,
  dailyChartTitle: "Eventos por dia",
  dailyChartLead: "VTs, validações e conclusões registradas em cada dia.",
  eventMixTitle: "Distribuição por etapa",
  eventMixLead: "Quantidade de cada tipo de evento no período.",
  funnelTitle: "Funil operacional",
  funnelLead: "Conversão entre assumir, VT, validação e conclusão.",
  operatorsTitle: "Operadores",
  operatorsLead: "Quem mais registrou VT e concluiu chamados.",
  symptomsTitle: "Reclamações por sintoma",
  symptomsLead: "Sintoma informado nas mensagens de VT registradas.",
  topClientsTitle: "Clientes com mais VTs",
  topClientsLead: "Contratos (ou MACs) com maior número de acionamentos no período.",
  emptyTratativas: "Nenhum evento de tratativa no período selecionado.",
  emptyDaily: "Sem eventos diários para exibir.",
  emptyOperators: "Nenhum acionamento ou conclusão atribuído a operadores.",
  emptySymptoms: "Nenhuma VT com sintoma registrado no período.",
  emptyTopClients: "Nenhum cliente com VT registrada no período.",
  durationHint: (minutes: number) => `Tempo médio até conclusão: ${minutes} min`,
  durationUnavailable: "Tempo médio até conclusão indisponível (sem conclusões no período).",
  kpiAssuncoes: "Chamados assumidos",
  kpiAssuncoesHint: "Registros que um operador passou a tratar",
  kpiAcionamentos: "VTs registradas",
  kpiAcionamentosHint: "Acionamentos de visita técnica no WhatsApp",
  kpiValidacoes: "Validações",
  kpiValidacoesHint: "Parecer do técnico sobre o reparo",
  kpiConcluidas: "Concluídos",
  kpiConcluidasHint: "Chamados encerrados pela operação",
  kpiAprovadas: "Aprovadas",
  kpiReprovadas: "Reprovadas",
  operatorAcionamentos: "Acionamentos",
  operatorConcluidas: "Conclusões",
  exportCsv: "Baixar CSV",
  exportAllHint: "Exporta todos os registros que correspondem aos filtros selecionados.",
  filtersLabel: "Filtros",
  statusLabel: "Status",
  tipoLabel: "Tipo",
  cfLabel: "CF executante",
  cfPlaceholder: "Opcional",
  cmtsLabel: "CMTS",
  cmtsPlaceholder: "Opcional",
  nodeLabel: "Node",
  nodePlaceholder: "Opcional",
  saudeLabel: "Saúde",
  vlanLabel: "VLAN BSOD",
  allTypes: "Todos",
  allHealth: "Todas",
  allVlan: "Todas",
} as const;

/** Metadados dos relatórios CSV disponíveis. */
export const RELATORIO_EXPORT_META = {
  ral: {
    title: METRIC_LABELS.sir.ral,
    description: "Listagem de RAL com status, tipo, CF, designação e datas.",
    exportPath: "/api/export/sir/rals",
    scope: "ral" as const,
  },
  rec: {
    title: METRIC_LABELS.sir.recScope,
    description: "Listagem REC/DSR/TCQ com cliente, designação, CF e datas.",
    exportPath: "/api/export/sir/recs",
    scope: "rec" as const,
  },
  bsod: {
    title: METRIC_LABELS.bsod.inventario,
    description: "Inventário PME com status, endereço, VLAN e métricas de sinal.",
    exportPath: "/api/export/bsod",
  },
} as const;
