/** Textos de interface centralizados. */
export const UI_COPY = {
  appName: "Empresarial",
  footer: "Claro — Equipe GRNO · Empresarial",
  emptyDefault: "Nenhum registro.",
  connectionOk: "OK",
  connectionError: "ERRO",
  noData: "SEM DADOS",
  tableSearchRal: "Buscar por número, CF ou designação…",
  tableSearchRec: "Buscar por número, cliente, CF ou designação…",
  tableSearchBsod: "Buscar por MAC, contrato, node ou CMTS…",
  sirViewDetails: "Ver detalhes",
  tratativaAssume: "Assumir",
  tratativaRelease: "Liberar",
  tratativaSince: "Desde",
  tratativaBusy: "…",
  tratativaAssumeError: "Não foi possível assumir a tratativa.",
  tratativaReleaseError: "Não foi possível liberar a tratativa.",
  acionamentoTitle: "Acionamento WhatsApp",
  acionamentoOpen: "Acionar",
  acionamentoTechnicianSection: "Dados do técnico",
  acionamentoPreviewSection: "Mensagem",
  acionamentoWhatsappTarget: "Menção no grupo",
  acionamentoJanela: "JANELA",
  acionamentoPreviewEmpty:
    "Preencha a janela e os dados do técnico (nome, cidade, login, RG) para visualizar a mensagem.",
  acionamentoMissingAddress:
    "Endereço ausente — rode o enrich PME no hfc-sls ou aguarde import Xpertrak.",
  acionamentoCopy: "Copiar e registrar",
  acionamentoCopied: "Copiado — cole no WhatsApp.",
  acionamentoRegisteredCopyFailed:
    "Acionamento registrado. Não foi possível copiar — selecione a mensagem e copie manualmente.",
  acionamentoClose: "Fechar",
  acionamentoLoading: "Carregando dados do registro…",
  acionamentoLoadError: "Não foi possível carregar o acionamento.",
  acionamentoSubmitError: "Não foi possível registrar o acionamento.",
  tratativaRequestValidacao: "Técnico pediu validação",
  tratativaRegisterValidacao: "Validar sinal",
  tratativaValidacaoTitle: "Validação do sinal",
  tratativaValidacaoHint:
    "O técnico solicitou validação a você (acionador). Registre o resultado e o FCA para",
  tratativaValidacaoOutcome: "Resultado",
  tratativaValidacaoFcaSection: "FCA",
  tratativaValidacaoFato: "Fato",
  tratativaValidacaoCausa: "Causa",
  tratativaValidacaoAcao: "Ação",
  tratativaValidacaoFatoPlaceholder: "O que foi identificado no atendimento",
  tratativaValidacaoCausaPlaceholder: "Causa raiz do problema",
  tratativaValidacaoAcaoPlaceholder: "Ação executada para normalizar",
  tratativaValidacaoSave: "Salvar validação",
  tratativaValidacaoError: "Não foi possível registrar a validação.",
  tratativaConcluir: "Concluir",
  tratativaWorkflowError: "Não foi possível avançar o fluxo da tratativa.",
} as const;

/** Rótulos das métricas do painel inicial. */
export const DASHBOARD_METRICS = {
  ral: { context: "RAL", label: "ABERTAS" },
  rec: { context: "REC", label: "ABERTOS" },
  bsod: { context: "INVENTÁRIO", label: "BSOD" },
  sirViewRal: "VER RAL",
  sirViewRec: "VER REC",
} as const;
